version: '2'

services:
  app:
    build: .
    restart: always
    ports:
      - 8080:80
    volumes:
      - app:/var/www/html
      - ./:/var/www/html/sites/all/modules/smaily_for_drupal
    depends_on:
      - database

  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: smaily1
    volumes:
      - database:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8888:80'
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: smaily1

volumes:
  app:
  database:
