version: '2'

services:
  app:
    build: .
    restart: always
    ports:
      - 8080:80
    volumes:
      - app:/var/www/html
      - ./:/var/www/html/modules/smaily_for_drupal

  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: smaily1
    volumes:
      - database:/var/lib/mysql
volumes:
  app:
  database:
