<?php

/**
 * @file
 * This is the core required file for Sendsmaily Subscribe.
 */

/**
 * Implements hook_page_build().
 *
 * @todo The block is not 6'th block always.
 */
function sendsmaily_subscribe_page_build(&$page) {
  drupal_add_js('(function($){$().ready(function(){
      //sendsmaily e-mail js validate
      $("#block-block-6 form").prepend(\'<div id="block-block-6-errors"></div>\');
      $("#block-block-6 form").submit(function(e){
        if(!validateEmail($("input[name$=\'email\']").val())){
          e.preventDefault();
          $("#block-block-6-errors").html(Drupal.t("Incorrect email address provided!"));
        }
      });
    });})(jQuery);

    //js validate function
    function validateEmail($email) {  var emailReg = /^([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?$/; return emailReg.test( $email );}',
  'inline');
}

/**
 * Implements hook_menu().
 */
function sendsmaily_subscribe_menu() {
  $items = array();

  $items['admin/config/people/sendsmaily'] = array(
    'title' => 'Sendsmaily',
    'description' => 'Sendsmaily integration configuration.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sendsmaily_subscribe_configuration_page', NULL),
    'access arguments' => array('administer sendsmaily'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function sendsmaily_subscribe_permission() {
  return array(
    'administer sendsmaily' => array(
      'title' => t('Administer sendsmaily'),
    ),
  );
}

/**
 * Admin form for setting domain and key.
 */
function sendsmaily_subscribe_configuration_page() {
  $form = array();

  $form['sendsmaily_options'] = array(
    '#title' => t('Subscription options'),
    '#type' => 'textarea',
    '#description' => t('List of key-value pairs on separated rows, that will be displayed on the registration form as checkboxes. ie. subscription1|Main news'),
    '#default_value' => variable_get('sendsmaily_options', ''),
  );

  $form['sendsmaily_domain'] = array(
    '#type' => 'textfield',
    '#title' => t('Domain'),
    '#default_value' => variable_get('sendsmaily_domain', ''),
    '#required' => TRUE,
  );

  $form['sendsmaily_key'] = array(
    '#type' => 'textfield',
    '#title' => t('API Key'),
    '#default_value' => variable_get('sendsmaily_key', ''),
    '#required' => TRUE,
  );

  $form['sendsmaily_autoresponder'] = array(
    '#type' => 'textfield',
    '#title' => t('Autoresponder'),
    '#default_value' => variable_get('sendsmaily_autoresponder', ''),
  );

  $form['sendsmaily_button_title'] = array(
    '#type' => 'textfield',
    '#title' => t('Subscribe button title'),
    '#default_value' => variable_get('sendsmaily_button_title', 'Subscribe to newsletter'),
    '#required' => TRUE,
  );

  $form['sendsmaily_success_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Success URL'),
    '#default_value' => variable_get('sendsmaily_success_url', ''),
    '#description' => t('For example: http://example.com Leave blank for redirect back'),
  );

  $form['sendsmaily_failure_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Failure URL'),
    '#default_value' => variable_get('sendsmaily_failure_url', ''),
    '#description' => t('For example: http://example.com Leave blank for redirect back'),
  );

  return system_settings_form($form);
}

/**
 * Implements hook_block_info().
 */
function sendsmaily_subscribe_block_info() {
  $blocks = array();

  $blocks['sendsmaily'] = array(
    'info' => t('Sendsmaily'),
  );

  return $blocks;
}

/**
 * Implements hook_form().
 */
function sendsmaily_subscribe_form($form, &$form_state) {
  $form['#action'] = 'https://' . variable_get('sendsmaily_domain', '') . '.sendsmaily.net/api/opt-in/';

  $form['name'] = array(
    '#title' => t('Name:'),
    '#type' => 'textfield',
    '#size' => FALSE,
    '#attributes' => array('placeholder' => t('Name')),
  );

  $form['email'] = array(
    '#title' => t('Email:'),
    '#type' => 'textfield',
    '#size' => FALSE,
    '#required' => TRUE,
    '#attributes' => array('placeholder' => t('Email')),
  );

  $form['autoresponder'] = array(
    '#type' => 'hidden',
    '#value' => variable_get('sendsmaily_autoresponder', ''),
  );

  $current_url = url(current_path(), array('absolute' => TRUE));
  $form['success_url'] = array(
    '#type' => 'hidden',
    '#value' => variable_get('sendsmaily_success_url') ?: $current_url,
  );

  $form['failure_url'] = array(
    '#type' => 'hidden',
    '#value' => variable_get('sendsmaily_failure_url') ?: $current_url,
  );

  if (variable_get('sendsmaily_options', '')) {
    $options = array();
    foreach (explode("\n", variable_get('sendsmaily_options', '')) as $line) {
      $values = explode("|", $line);
      $options[trim($values[0])] = trim($values[1]);
    }
    foreach ($options as $field => $label) {
      $form['category_' . $field] = array(
        '#type' => 'checkbox',
        '#title' => $label,
      );
    }
  }

  $form['join'] = [
    // #name 'op' is recognized as a custom field by Smaily, leaving it blank here.
    '#name' => '',
    '#type' => 'submit',
    '#value' => t(variable_get('sendsmaily_button_title', 'Subscribe to newsletter')),
    '#default_value' => t('Subscribe to newsletter'),
  ];

  // Remove hidden form elements to not send them to Smaily as a field.
  $form['#pre_render'][] = 'removeHiddenDrupalInputs';
  return $form;
}

/**
 * Remove form_id and form_build_id as to not send them to Smaily as fields.
 *
 * @param array $form
 *   Form before it is rendered for display.
 *
 * @return array
 *   Form without form_id and form_build_id hidden elements.
 */
function removeHiddenDrupalInputs(array $form) {
  unset($form['form_build_id']);
  unset($form['form_id']);
  return $form;
}

/**
 * Implements hook_block_view().
 */
function sendsmaily_subscribe_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'sendsmaily':
      $sendsmaily_domain = variable_get('sendsmaily_domain', '');
      $sendsmaily_key = variable_get('sendsmaily_key', '');

      $block['subject'] = t('Subscribe to our newsletter');
      if (strlen($sendsmaily_domain) && $sendsmaily_key) {
        $block['content'] = drupal_get_form('sendsmaily_subscribe_form');
      }
      else {
        $block['content'] = t("No domain or key found. Please !configure Sendsmaily Subscribe!", array('!configure' => l(t('configure'), 'admin/config/people/sendsmaily')));
      }

      break;
  }

  return $block;
}
